#pragma config(Motor,  port2,           lf,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           lb,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rf,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rb,            tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
		//Drive(Movement of Whole Robot)

	//RIGHT SIDE = CHANNEL 2 - CHANNEL 1
	//LEFT SIDE = CHANNEL 2+ CHANNEL 1 1

	  motor[rb] = -vexRT[Ch2]+vexRT[Ch1];
		motor[rf] = -vexRT[Ch2]+vexRT[Ch1];
		motor[lf] = vexRT[Ch2]+vexRT[Ch1];
		motor[lb] = vexRT[Ch2]+vexRT[Ch1];


}
