#pragma config(Motor,  port8,           rdmotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           ldmotor, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task main()

{
	while (true)
	{

		if (vexRT(Btn5U) == 1){
			motor(rdmotor) = -63;
			motor(ldmotor) = 63;
		}
//Closing.
		else {
			motor(rdmotor) = 0;
			motor(ldmotor) = 0;
			}

		if (vexRT(Btn5D) == 1){
			motor(rdmotor) = 63;
			motor(ldmotor)= -63;
//Opening.
		}

		else {
			motor(rdmotor) = 0;
			motor(ldmotor) = 0;
	}

}
}



