#pragma config(Motor,  port3,           lbmotor,       tmotorNone, openLoop)
#pragma config(Motor,  port5,           lfmotor,       tmotorNone, openLoop)
#pragma config(Motor,  port6,           rfmotor,       tmotorNone, openLoop)
#pragma config(Motor,  port7,           rbmotor,       tmotorNone, openLoop)
#pragma config(Motor,  port8,           rdmotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           ldmotor, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(true){
		motor[rbmotor] = vexRT[Ch3];
		motor[rfmotor] = vexRT[Ch3];
		motor[lfmotor] = -vexRT[Ch2];
		motor[lbmotor] = -vexRT[Ch2];
//Movement of Whole Robot
	if (vexRT(Btn5U) == 1){
			motor(rdmotor) = -63;
			motor(ldmotor) = 63;
		}
//Closing.
		else {
			motor(rdmotor) = 0;
			motor(ldmotor) = 0;
			}

		if (vexRT(Btn5D) == 1){
			motor(rdmotor) = 63;
			motor(ldmotor)= -63;
//Opening.
		}

		else {
			motor(rdmotor) = 0;
			motor(ldmotor) = 0;
	}
}

}
