#pragma config(Motor,  port3,           lbmotor,       tmotorNone, openLoop)
#pragma config(Motor,  port5,           lfmotor,       tmotorNone, openLoop)
#pragma config(Motor,  port6,           rfmotor,       tmotorNone, openLoop)
#pragma config(Motor,  port7,           rbmotor,       tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
		motor[rbmotor] = vexRT[Ch3];
		motor[rfmotor] = vexRT[Ch3];
		motor[lfmotor] = vexRT[Ch2];
		motor[lbmotor] = vexRT[Ch2];


}

}
