#pragma config(Sensor, in1,    leftpoten,      sensorPotentiometer)
#pragma config(Sensor, in2,    rightpoten,     sensorPotentiometer)
#pragma config(Motor,  port2,           jawleft,       tmotorNone, openLoop)
#pragma config(Motor,  port3,           lbmotor,       tmotorNone, openLoop)
#pragma config(Motor,  port4,           jawright,      tmotorNone, openLoop)
#pragma config(Motor,  port5,           lfmotor,       tmotorNone, openLoop)
#pragma config(Motor,  port6,           rfmotor,       tmotorNone, openLoop)
#pragma config(Motor,  port7,           rbmotor,       tmotorNone, openLoop)
#pragma config(Motor,  port8,           rdmotor,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           ldmotor,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


// in this program, it "supposedly" allows multiple command to go off at the same time
// ask if this program needs to set variables for int
// ask about ptlw programming language

task main()
{
	{
  //Trigger
 if(vexRT[Btn5U] == 1)

	//setting the timer
  clearTimer(T1);

  //Drivng Forward

  while(time1[T1] < 2000)
 	{
		motor[lfmotor] = -127;
		motor[lbmotor] = -127;
		motor[rbmotor] = 127;
		motor[rfmotor] = 127;
		motor[ldmotor] = 63;
		motor[rdmotor] = 63;
}


  //Motors drive back.
  	motor[lbmotor] = 127;
  	motor[lfmotor] = 127;
  	motor[rfmotor] = -127;
  	motor[rbmotor] = -127;
  	wait1Msec(3000);
}
}
