#pragma config(Motor,  port8,           rightmotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          leftmotor,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{

		if (vexRT(Btn5U) == 1){
			motor(rightmotor) = 127;
			motor(leftmotor) = 127;
		}


		else {
			motor(rightmotor) = 0;
			motor(leftmotor) = 0;
		}

}

}
