<<<<<<< HEAD
#pragma config(Motor,  port2,           motortwo,      tmotorNone, openLoop)
#pragma config(Motor,  port3,           motorthree,    tmotorNone, openLoop)
#pragma config(Motor,  port4,           motorfour,     tmotorNone, openLoop)
#pragma config(Motor,  port5,           motorfive,     tmotorNone, openLoop)
#pragma config(Motor,  port6,           motorsix,      tmotorNone, openLoop)
#pragma config(Motor,  port7,           motorseven,    tmotorNone, openLoop)
#pragma config(Motor,  port8,           rightmotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftmotor,     tmotorVex393_MC29, openLoop)
=======
#pragma config(Motor,  port8,           rightmotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,          leftmotor,     tmotorVex393_HBridge, openLoop)
>>>>>>> 1ac02a0d9b7e492510afc6048a565fd608dbfcb9
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
{

		if (vexRT(Btn5U) == 1){
			motor(rightmotor) = -127;
			motor(leftmotor) = 127;
		}


		else {
			motor(rightmotor) = 0;
			motor(leftmotor) = 0;
		}

		if (vexRT(Btn6U) == 1){
			motor(motortwo) = 120;
			motor(motorthree)= 120;


		}

		else {
			motor(motortwo) = 0;
			motor(motorthree) = 0;


		}

}




 }
