#pragma config(Sensor, dgtl9,  encoderight,   sensorQuadEncoder)
#pragma config(Sensor, dgtl11, encodeleft,    sensorQuadEncoder)
#pragma config(Motor,  port2,           lf,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           lb,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rb,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rf,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           lows1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           lows2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           high1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           high2,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task 1                            */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	/*
	//OLD WORKING CODE ======= 1 POINT CONSISTENT
	//Forward
	motor[lb] = -65;
	motor[lf] = -65;
	motor[rb] = 60;
	motor[rf] = 60;
	motor[lows1] = 127;
	motor[lows2] = -127;
	wait1Msec(1100);


	//back
	motor[lb] = 65;
	motor[lf] = 65;
	motor[rb] = -60;
	motor[rf] = -60;
	wait1Msec(1500);

	//stop
	motor[lb] = 0;
	motor[lf] = 0;
	motor[rb] = 0;
	motor[rf] = 0;
	motor[lows1] = 0;
	motor[lows2] = 0;
	wait1Msec(3000);

*/




}




// ..........................................................................
// Insert user code here.
// ..........................................................................

// Remove this function call once you have "real" code.
//AutonomousCodePlaceholderForTesting();


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop
	float speedfactor1=0.45;
	//float speedfactor2= 0.4;
	while (true)
	{

		//Drive
		motor[rb] = -vexRT[Ch2];
		motor[rf] = -vexRT[Ch2]*speedfactor1;
		motor[lb] = vexRT[Ch3];
		motor[lf] = vexRT[Ch3];


		//Vacuum
		if (vexRT(Btn6U) == 1 && vexRT(Btn6D)==0)
		{
			motor[lows1] = -105;
			motor[lows2] =  105;
		}
		else if (vexRT[Btn6D] == 1 && vexRT(Btn6U) == 0)
		{
			motor[lows1] = 105;
			motor[lows2] = -105;
		}
		else
		{
			motor[lows1] = 0;
			motor[lows2] = 0;

			//Cockblock
			if (vexRT(Btn5U) == 1 && vexRT(Btn5D)==0)
			{
				motor[high1] = -85;
				motor[high2] =  85;
			}
			else if (vexRT[Btn5D] == 1 && vexRT(Btn5U) == 0)
			{
				motor[high1] = 85;
				motor[high2] = -85;
			}
			else
			{
				motor[high1] = 0;
				motor[high2] = 0;



			}
		}
	}

}










//Shrine of Wisdom and Fortune:
//
//							"Let them fight." -Dr. Ishiro Seriwaza

//





//Archive:
/*			motor[lb] = -100;
motor[lf] = 100;
motor[rb] = -100;
motor[rf] = 100;
wait1Msec(3000);
motor[lb] = 0;
motor [lf] = 0;
motor[rb] = 0;
motor[rf] = 0;
motor[lows1] = -50;
motor[lows2] = 50;
motor[high1] = -50;
motor[high2] = 50;
wait1Msec(3000);
motor[lows1] = 0;
motor[lows2] = 0;
motor[high1] = 0;
motor[high2] = 0;
motor[lb] = 35;
motor[lf] = -35;
motor[rb] = 65;
motor[rf] = -65;
wait1Msec(2000);
motor[lows1] = 0;
motor[lows2] = 0;
motor[high1] = 0;
motor[high2] = 0;
motor[lb] = 90;
motor[lf] = -90;
motor[rb] = 90;
motor[rf] = -90;
wait1Msec(5000);
motor[lb] = 0;
motor[lf] = 0;
motor[rb] = 0;
motor[rf] = 0;
motor[high1] = -50;
motor[high2] = 50;
motor[lows1] = 50;
motor[lows2] = -50;
wait1Msec(2000);


Comp Auton
//Auton Tester
if (vexRT(Btn8U) == 1 && vexRT(Btn8D)==0)
{
//Forward
motor[lb] = -65;
motor[lf] = -65;
motor[rb] = 60;
motor[rf] = 60;
wait1Msec(800);
//right
motor[lb] = -60;
motor[lf] = -60;
motor[rb] = -60;
motor[rf] = -60;
wait1Msec(600);
//forward
motor[lb] = -67;
motor[lf] = -67;
motor[rb] = 62;
motor[rf] = 62;
wait1Msec(2200);
motor[lows1]=-127;
motor[lows2]=127;
//right
motor[lb] = -60;
motor[lf] = -60;
motor[rb] = -60;
motor[rf] = -60;
wait1Msec(800);
//forward
motor[lb] = -30;
motor[lf] = -30;
motor[rb] = 25;
motor[rf] = 25;
wait1Msec(150);
//drop
motor[lows1] = 127;
motor[lows2] = -127;
wait1Msec(4000);
//back
motor[lb] = 50;
motor[lf] = 50;
motor[rb] = -45;
motor[rf] = -45;
wait1Msec(150);
//stop
motor[lb] = 0;
motor[lf] = 0;
motor[rb] = 0;
motor[rf] = 0;
motor[lows1] = 0;
motor[lows2] = 0;
wait1Msec(3000);
}

else
{
motor[lb] = 0;
motor[lf] = 0;
motor[rb] = 0;
motor[rf] = 0;
motor[lows1] = 0;
motor[lows2] = 0;



V2
//Forward
	motor[lb] = -65;
	motor[lf] = -65;
	motor[rb] = 60;
	motor[rf] = 60;
	wait1Msec(800);
	//right
	motor[lb] = -60;
	motor[lf] = -60;
	motor[rb] = -60;
	motor[rf] = -60;
	wait1Msec(600);
	//forward
	motor[lb] = -67;
	motor[lf] = -67;
	motor[rb] = 62;
	motor[rf] = 62;
	wait1Msec(2200);
	motor[lows1]=-127;
	motor[lows2]=127;
	//right
	motor[lb] = -60;
	motor[lf] = -60;
	motor[rb] = -60;
	motor[rf] = -60;
	wait1Msec(800);
	//forward
	motor[lb] = -30;
	motor[lf] = -30;
	motor[rb] = 25;
	motor[rf] = 25;
	wait1Msec(150);
	//drop
	motor[lows1] = 127;
	motor[lows2] = -127;
	wait1Msec(4000);
	//back
	motor[lb] = 50;
	motor[lf] = 50;
	motor[rb] = -45;
	motor[rf] = -45;
	wait1Msec(225);
	//stop
	motor[lb] = 0;
	motor[lf] = 0;
	motor[rb] = 0;
	motor[rf] = 0;
	motor[lows1] = 0;
	motor[lows2] = 0;
	wait1Msec(3000);



/* Courtesy of Ethan A. Collis, Circa 2019*/
