#pragma config(Sensor, in1,    SensorR,        sensorPotentiometer)
#pragma config(Sensor, in2,    SensorL,        sensorPotentiometer)
#pragma config(Motor,  port2,           wiilllR,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           wiilllL,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Arm1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Arm2,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Pickup1,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Pickup2,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{


while(true){
int x = SensorValue[in1];
int y = SensorValue[in2];

motor[wiilllR] = -vexRT[Ch2];
motor[wiilllL] = vexRT[Ch2];

motor[wiilllR] = -vexRT[Ch4];
motor[wiilllL]
if (vexRT[Btn6U]){
	motor[Arm1] = -50;
  motor[Arm2] = 50;
}
else if (vexRT[Btn6D]){
	motor[Arm1] = 50;
	motor[Arm2] = -50;
}
else{
	motor[Arm1] = 0;
	motor[Arm2] = 0;
}

int preDiff = x - y;
x = SensorValue[in1];
y = SensorValue[in2];
motor[Arm1] = -0.05*(x-y) + 0.005*(preDiff-x+y);
motor[Arm2] = 0.05*(y-x) - 0.005*(preDiff-y+x);

}
}
