#pragma config(Motor,  port2,           topright,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           backleft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backright,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           topleft,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           hand,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
/*/void forward(int t) {
forward
motor[topleft]= 100;
motor[backleft]= 100;
motor[topright]= -100;
motor[backright]= -100;
wait1Msec(t);*/
{
	// forward
	motor[topleft]= 100;
	motor[backleft]= 100;
	motor[topright]= -65;
	motor[backright]= -65;
	wait1Msec(1970);

	//turning
	motor[topleft]= -110;
	motor[backleft]= -110;
	motor[topright]= -100;
	motor[backright]= -100;
	wait1Msec(500);

	//forward
	motor[topleft]= 100;
	motor[backleft]= 100;
	motor[topright]= -70;
	motor[backright]= -70;
	wait1Msec(880);

//backwards climb
	motor[topleft]= -127;
	motor[backleft]= -127;
	motor[topright]= 80;
	motor[backright]= 80;
	wait1Msec(2500);

	motor[topleft]= 0;
	motor[backleft]= 0;
	motor[topright]= 0;
	motor[backright]= 0;

}
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop
float speedFactor = 0.6;
{
while (1==1)
{
//hand goes up

	if(vexRT[Btn6U] == 1)
{
 motor[hand]= 127;
}
else if(vexRT[Btn5U]== 1)
{
	motor[hand]= -127;
}
else
{motor[hand] =0;}


//hand balanced
/*
if(vexRT[Btn8D] == 1)
{
	motor[hand]=0;
	motor[hand]=0;
}
else if(vexRT[Btn6U] == 1 && vexRT[Btn6D] == 1)

	motor[hand]=127;
	motor[hand]=-127;
*/
//open the claw

if(vexRT[Btn8U]==1)
{
 motor[claw]= 127;
}
else if(vexRT[Btn8D]== 1)
{
	motor[claw]= -127;
}else
	{
		motor[claw]=0;
}
//wheels
  motor[topleft]=-vexRT[Ch3]+vexRT[Ch1];
	motor[backleft]=-vexRT[Ch3]+vexRT[Ch1];
	motor[topright]=(vexRT[Ch3]+vexRT[Ch1])*speedFactor;
	motor[backright]=(vexRT[Ch3]+ vexRT[Ch1])*speedFactor;

/*int leftSpeed = 127;
int rightSpeed =-100;

//wheels different speed
if(vexRT[Ch3] == 1)
{
motor [topleft]= leftSpeed;
motor [backleft]= leftSpeed;
motor [topright]= rightSpeed;
motor [backright]= rightSpeed;*/

}}

  while (true)
  {
    // This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.

    // ........................................................................
    // Insert user code here. This is where you use the joystick values to
    // update your motors, etc.
    // ........................................................................

    // Remove this function call once you have "real" code.
    UserControlCodePlaceholderForTesting();
  }
}
