#pragma config(Motor,  port2,           topright,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           backleft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backright,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           topleft,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           hand,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while (1==1)
{
//hand goes up

	if(vexRT[Btn6U] == 1)
{
 motor[hand]= 127;
}
else if(vexRT[Btn6D]== true)
{
	motor[hand]= -127;
}else
	{
		motor[hand]=0;
}

//hand balanced
/*
if(vexRT[Btn8D] == 1)
{
	motor[hand]=0;
	motor[hand]=0;
}
else if(vexRT[Btn6U] == 1 && vexRT[Btn6D] == 1)

	motor[hand]=127;
	motor[hand]=-127;
*/
//open the claw

if(vexRT[Btn8U]==1)
{
 motor[claw]= 127;
}
else if(vexRT[Btn8D]== true)
{
	motor[claw]= -127;
}else
	{
		motor[claw]=0;
}
//wheels
	motor[topleft]=-vexRT[Ch3]+vexRT[Ch1];
	motor[backleft]=-vexRT[Ch3]+vexRT[Ch1];
	motor[topright]=vexRT[Ch3]+vexRT[Ch1];
	motor[backright]=vexRT[Ch3]+ vexRT[Ch1];
}}
