#pragma config(Sensor, in1,    shoulder,       sensorPotentiometer)
#pragma config(Sensor, in2,    wrist,          sensorPotentiometer)
#pragma config(Motor,  port1,           rightmotor,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           armmotor1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           armmotor2,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           lift2,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           lift1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          leftmotor,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int a;
	int b;

	a = SensorValue[in1];
	b = SensorValue[in2];

while(1==1)
{
	a = SensorValue[in1];
	b = SensorValue[in2];
	motor[rightmotor] = (-vexRT[Ch3] + vexRT[Ch4])/2;
  motor[leftmotor] = (vexRT[Ch3] + vexRT[Ch4])/2;
// moving
  if(vexRT[Btn5U] == true)
{
	motor[lift1] = -127;
	motor[lift2] = 127;

}


	else
{
	motor[lift1] = 0;
	motor[lift2] = 0;
}
// press 5U to make the lift/hand go up
  if(vexRT[Btn5D] == true)
  {
  	motor[port9] = 127;
  	motor[port8] = -127;
	}
	else
	{
		motor[port9] = 0;
		motor[port8] = 0;
	}
//press 5D to make the lift/hand go down
	if(vexRT[Btn6U] == true)
	{
		//errorTotal = 450-a+errorTotal;
		motor[armmotor1] = -127;
		motor[armmotor2] = 127;
		motor[lift1] = -0.02*(a+b-3500);
		motor[lift2] = 0.02*(a+b-3500);
// arm moving while lift keep level

		}
	else if(vexRT[Btn6D] == true)
	{
		motor[armmotor1] = 127;
		motor[armmotor2] = -127;
		motor[lift1] = -0.02*(a+b-3500);
		motor[lift2] = 0.02*(a+b-3500);
//arm move down while lift keep level
  }
 else
 {
   motor[armmotor1] = 0;
   motor[armmotor2] = 0;

}


}
}
